version: '3'
services:
  app:
    build: .
    depends_on:
      - postgresapp
      - redisapp
      - mongoapp
    environment:
      NODE_ENV: development
      PORT: 5000
    ports:
      - '5000:5000'
    command: yarn dev
    volumes:
      - .:/usr/src/
      - ./node_modules:/usr/src/node_modules
    links:
      - postgresapp
      - redisapp
      - mongoapp
    networks:
      - myapp

  postgresapp:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: development
    volumes:
      - ./src/database:/var/lib/postgresql/data
    networks:
      - myapp

  redisapp:
    image: redis:alpine
    container_name: cache
    ports:
      - '6379:6379'
    networks:
      - myapp

  mongoapp:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./src/database/mongo:/var/lib/mongodb/data
    networks:
      - myapp
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: admin
    #   MONGO_INITDB_ROOT_PASSWORD: docker
    #   MONGO_INITDB_DATABASE: gobarber

networks:
  myapp:
    driver: bridge
